version: '3.8'

services:
  mongo: 
    image: mongo
    container_name: mongo_by_compose_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  express-app:
    build: ./
    container_name: express_by_compose_container
    ports:
      - "3030:3030"
    depends_on:
      - mongo

volumes:
  mongo_data:
